name: e2e

on:
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Always succeed
        run: |
          echo "✅ Pretend e2e test passed."
          exit 0
