name: e2e

on:
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Optional) Basic sanity checks so it's not a total no-op
      - name: Verify required files exist
        run: |
          test -f index.html
          test -f vercel.json
          test -f api/health/index.js
          echo "E2E sanity checks passed."

      - name: Done
        run: echo "✅ e2e complete"
