name: Require BOTH Code Owners

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
  pull_request_review:
    types: [submitted, edited, dismissed]

permissions:
  contents: read
  pull-requests: read

jobs:
  check-approvals:
    name: both-codeowners
    runs-on: ubuntu-latest
    env:
      REQUIRED_OWNERS: alenRI051,nova-ai
    steps:
      - name: Evaluate approvals from required owners
        uses: actions/github-script@v7
        with:
          script: |
            const REQUIRED = process.env.REQUIRED_OWNERS.split(',').map(s => s.trim()).filter(Boolean);
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const prNum = context.payload.pull_request?.number || context.issue.number;

            const reviews = await github.paginate(github.rest.pulls.listReviews, {
              owner, repo, pull_number: prNum, per_page: 100
            });

            const latestByUser = new Map();
            for (const r of reviews) {
              latestByUser.set(r.user.login.toLowerCase(), {state: r.state, submitted_at: r.submitted_at});
            }

            const missing = [];
            for (const u of REQUIRED) {
              const rec = latestByUser.get(u.toLowerCase());
              if (!rec || rec.state !== 'APPROVED') {
                missing.push(u);
              }
            }

            if (missing.length) {
              core.setFailed(`Missing required Code Owner approvals from: ${missing.join(', ')}`);
            } else {
              core.info(`All required Code Owners approved: ${REQUIRED.join(', ')}`);
            }
